FROM python:3.12-slim

WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Download NLTK data at build time
RUN python -m nltk.downloader -d /app/nltk_data punkt

# Copy app
COPY . .

# Set environment variable for NLTK
ENV NLTK_DATA=/app/nltk_data

CMD ["python", "main.py"]
